@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Контекстная диаграмма - Система умного дома

' Пользователи системы
Person(user, "Пользователь", "Хозяин дома, который хочет контролировать температуру в комнатах")

' Основная система (то, что мы разрабатываем)
System(smart_home, "Управление устройствами", "Приложение на Go, которое управляет датчиками температуры в доме")

' Внешние системы
System_Ext(temp_service, "Сервис погоды", "Внешний сервис, который дает информацию о температуре на улице")
System_Ext(sensors, "Датчики в доме", "Физические датчики температуры в каждой комнате")

' База данных
SystemDb(database, "База данных", "PostgreSQL - здесь храним информацию о датчиках")

' Связи между компонентами
Rel(user, smart_home, "Смотрит температуру, настраивает датчики", "Веб-сайт/приложение")
Rel(smart_home, database, "Сохраняет и читает данные", "SQL")
Rel(smart_home, temp_service, "Получает данные о погоде", "HTTP API")
Rel(sensors, smart_home, "Отправляет показания температуры", "WiFi")

@enduml
